/**
 * pdf.js — Agri Monitor MRV Export Engine
 * CHANGE TechLab | Uttarakhand
 *
 * Exports: PDF, JSON, GeoJSON, CSV, PNG map snapshot
 * Depends on: jsPDF (vendor), MRVUtils, MRVCalculator
 */

'use strict';

const MRVExporter = (() => {

  // ─── PDF Export ──────────────────────────────────────────────

  async function exportPDF(record) {
    const { jsPDF } = window.jspdf || {};
    if (!jsPDF) { alert('PDF library not loaded. Please try again.'); return; }

    const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const PAGE_W = 210, PAGE_H = 297;
    const MARGIN = 15;
    const COL    = PAGE_W - MARGIN * 2;
    let   y      = MARGIN;

    const GREEN  = [22, 163, 74];
    const DARK   = [13, 17, 23];
    const GRAY   = [100, 110, 120];
    const LIGHT  = [245, 248, 245];

    function newPage() {
      doc.addPage();
      y = MARGIN;
      _pageHeader();
    }

    function checkY(needed = 20) {
      if (y + needed > PAGE_H - MARGIN) newPage();
    }

    function _pageHeader() {
      doc.setFillColor(...GREEN);
      doc.rect(0, 0, PAGE_W, 10, 'F');
      doc.setFontSize(7); doc.setTextColor(255, 255, 255);
      doc.text('Agri Monitor MRV — CHANGE TechLab | Uttarakhand', MARGIN, 7);
      doc.text(`MRV-ID: ${record.mrv_id}`, PAGE_W - MARGIN, 7, { align: 'right' });
      y = Math.max(y, 15);
    }

    function heading(text, size = 13) {
      checkY(12);
      doc.setFontSize(size); doc.setTextColor(...GREEN); doc.setFont(undefined, 'bold');
      doc.text(text, MARGIN, y); y += size * 0.5 + 3;
      doc.setFontSize(9); doc.setTextColor(...DARK); doc.setFont(undefined, 'normal');
    }

    function row(label, value, indent = 0) {
      checkY(7);
      doc.setFontSize(9); doc.setTextColor(...GRAY);
      doc.text(String(label), MARGIN + indent, y);
      doc.setTextColor(...DARK);
      doc.text(String(value || '—'), MARGIN + 80 + indent, y);
      y += 6;
    }

    function divider() {
      doc.setDrawColor(...GREEN); doc.setLineWidth(0.3);
      doc.line(MARGIN, y, PAGE_W - MARGIN, y); y += 4;
    }

    function badge(text, color = GREEN) {
      doc.setFillColor(...color);
      doc.roundedRect(MARGIN, y, doc.getTextWidth(text) + 6, 7, 2, 2, 'F');
      doc.setFontSize(8); doc.setTextColor(255, 255, 255);
      doc.text(text, MARGIN + 3, y + 5.2); y += 10;
    }

    // ── Cover
    doc.setFillColor(...DARK);
    doc.rect(0, 0, PAGE_W, PAGE_H, 'F');

    doc.setFillColor(...GREEN);
    doc.rect(0, 0, PAGE_W, 60, 'F');

    doc.setFontSize(22); doc.setTextColor(255, 255, 255); doc.setFont(undefined, 'bold');
    doc.text('MRV FOUNDATION REPORT', PAGE_W / 2, 30, { align: 'center' });
    doc.setFontSize(11); doc.setFont(undefined, 'normal');
    doc.text('Monitoring | Reporting | Verification', PAGE_W / 2, 40, { align: 'center' });
    doc.text('CHANGE TechLab — Agri Monitor Platform', PAGE_W / 2, 50, { align: 'center' });

    doc.setFillColor(...LIGHT);
    doc.rect(MARGIN, 70, COL, 50, 'F');
    doc.setFontSize(10); doc.setTextColor(...DARK);
    const f = record.farmer;
    doc.text(`MRV ID: ${record.mrv_id}`, MARGIN + 5, 82);
    doc.text(`Farmer: ${f.name}`, MARGIN + 5, 90);
    doc.text(`Village: ${f.village}, ${f.block}, ${f.district}`, MARGIN + 5, 98);
    doc.text(`Created: ${MRVUtils?.formatDate(record.created_at) || record.created_at}`, MARGIN + 5, 106);
    doc.text(`Status: ${record.status.toUpperCase()}`, MARGIN + 5, 114);

    // Status badge on cover
    const statusClr = record.status === 'verified' ? [22, 163, 74]
                    : record.status === 'submitted' ? [59, 130, 246]
                    : [156, 163, 175];
    doc.setFillColor(...statusClr);
    doc.rect(PAGE_W - MARGIN - 40, 70, 40, 10, 'F');
    doc.setFontSize(9); doc.setTextColor(255, 255, 255);
    doc.text(record.status.toUpperCase(), PAGE_W - MARGIN - 20, 76.5, { align: 'center' });

    doc.setFontSize(8); doc.setTextColor(...GRAY);
    doc.text('This report is generated by Agri Monitor and is for internal MRV documentation purposes.', PAGE_W / 2, PAGE_H - 20, { align: 'center' });
    doc.text('For formal carbon credit issuance, third-party verification is required.', PAGE_W / 2, PAGE_H - 15, { align: 'center' });

    // ── Page 2+
    doc.addPage();
    y = MARGIN; _pageHeader();

    // Section 1 — Farmer
    heading('1. Farmer Profile');
    row('Name', f.name); row('Mobile', f.mobile);
    row('Aadhaar (last 4)', f.aadhaar_last4 ? '****' + f.aadhaar_last4 : '—');
    row('Village', f.village); row('Block', f.block);
    row('District', f.district); row('State', f.state || 'Uttarakhand');
    row('CLF / SHG', f.clf_shg);
    row('Enumerator', f.enumerator_name);
    if (f.lat) row('GPS', `${f.lat?.toFixed(6)}, ${f.lng?.toFixed(6)}`);
    divider();

    // Section 2 — Land
    heading('2. Land / GIS Boundary');
    const l = record.land;
    row('Khasra No.', l.khasra_number); row('Khata No.', l.khata_number);
    row('Area (ha)', l.area_ha); row('Area (acres)', l.area_acres);
    row('Area (bigha)', l.area_bigha);
    row('Entry Method', l.entry_method);
    if (l.centroid) row('Centroid', `${l.centroid.lat?.toFixed(6)}, ${l.centroid.lng?.toFixed(6)}`);
    if (l.polygon_coords?.length) row('Polygon Points', l.polygon_coords.length + ' vertices');
    divider();

    // Section 3 — Baseline
    checkY(40);
    heading('3. Baseline Data');
    const b = record.baseline;
    row('Season', b.season); row('Primary Crop', b.primary_crop);
    row('Crop Variety', b.crop_variety);
    row('Sowing Date', b.sowing_date); row('Harvest Date', b.harvest_date);
    row('Irrigation', b.irrigation_source);
    row('Fertilizer', b.fertilizer_type);
    row('Baseline Yield', `${b.baseline_yield_kg} ${b.baseline_yield_unit}`);
    divider();

    // Section 4 — Interventions
    checkY(40);
    heading('4. Carbon Interventions');
    const iv = record.interventions;
    const intNames = { awd: 'AWD (Alternate Wetting & Drying)', soc: 'SOC Enhancement', biochar: 'Biochar Application', agroforestry: 'Agroforestry', compost: 'Compost / FYM', residue: 'Crop Residue Management' };
    Object.entries(iv).forEach(([key, val]) => {
      if (val?.enabled) {
        checkY(8);
        doc.setFontSize(9); doc.setTextColor(...GREEN); doc.setFont(undefined, 'bold');
        doc.text(`✓ ${intNames[key] || key}`, MARGIN + 2, y); y += 6;
        doc.setFont(undefined, 'normal'); doc.setTextColor(...DARK);
        if (val.area_ha)       row('  Area', `${val.area_ha} ha`, 2);
        if (val.amount_tons)   row('  Amount', `${val.amount_tons} tons`, 2);
        if (val.tree_count)    row('  Trees', val.tree_count, 2);
        if (val.species)       row('  Species', val.species, 2);
      }
    });
    divider();

    // Section 5 — Carbon Results
    checkY(60);
    heading('5. Carbon Calculation Results');
    const c = record.carbon;
    if (c?.breakdown) {
      const entries = Object.entries(c.breakdown).filter(([,v]) => v > 0);
      entries.forEach(([k, v]) => row(k.replace('_tco2e', '').toUpperCase(), `${v} tCO₂e`));
    }
    y += 2;
    doc.setFontSize(11); doc.setFont(undefined, 'bold'); doc.setTextColor(...GREEN);
    doc.text(`Gross: ${c.gross_tco2e} tCO₂e`, MARGIN, y); y += 7;
    doc.text(`Net:   ${c.net_tco2e} tCO₂e`, MARGIN, y); y += 7;
    doc.setTextColor(252, 211, 77);
    doc.text(`Est. Value: ₹${Number(c.credit_value_inr).toLocaleString()} (India CCTS)`, MARGIN, y); y += 7;
    doc.setFont(undefined, 'normal'); doc.setTextColor(...DARK);
    row('Methodology', c.methodology);
    divider();

    // Section 6 — Yield
    checkY(40);
    heading('6. Yield Data');
    const yd = record.yield_data;
    row('Actual Yield', `${yd.actual_yield_kg} ${yd.yield_unit}`);
    row('Market Price', `₹${yd.market_price_inr}/quintal`);
    row('Income (before)', `₹${yd.income_before_inr}`);
    row('Income (after)',  `₹${yd.income_after_inr}`);
    row('Income gain',    `₹${yd.income_delta_inr}`);
    divider();

    // Section 7 — Timeline
    if (record.timeline?.length) {
      checkY(30);
      heading('7. Monitoring Timeline');
      record.timeline.forEach(ev => {
        checkY(8);
        doc.setFontSize(8.5); doc.setTextColor(...GRAY);
        doc.text(`${ev.date}`, MARGIN, y);
        doc.setTextColor(...DARK);
        doc.text(`${ev.activity}`, MARGIN + 30, y);
        if (ev.notes) { y += 5; doc.setFontSize(8); doc.setTextColor(...GRAY); doc.text(`   ${ev.notes}`, MARGIN + 4, y); }
        y += 6;
      });
      divider();
    }

    // Footer
    checkY(20);
    doc.setFontSize(8); doc.setTextColor(...GRAY);
    doc.text(`Generated by Agri Monitor | ${new Date().toLocaleString('en-IN')} | Schema v${record.schema_version}`, MARGIN, y);

    doc.save(`${record.mrv_id}_MRV_Report.pdf`);
  }

  // ─── JSON Export ─────────────────────────────────────────────

  function exportJSON(record) {
    MRVUtils?.downloadJSON(record, `${record.mrv_id}_MRV.json`);
  }

  // ─── GeoJSON Export ──────────────────────────────────────────

  function exportGeoJSON(record) {
    const geojson = record.land?.geojson || MRVUtils?.latlngsToGeoJSON(record.land?.polygon_coords, {
      mrv_id:   record.mrv_id,
      farmer:   record.farmer?.name,
      district: record.farmer?.district,
      area_ha:  record.land?.area_ha
    });
    if (!geojson) { alert('No polygon data available for GeoJSON export.'); return; }
    MRVUtils?.downloadGeoJSON({ type: 'FeatureCollection', features: [geojson] }, `${record.mrv_id}_boundary.geojson`);
  }

  // ─── CSV Export ──────────────────────────────────────────────

  function exportCSV(record) {
    const headers = ['MRV ID', 'Farmer Name', 'Mobile', 'Village', 'Block', 'District', 'Area (ha)', 'Interventions', 'Gross tCO2e', 'Net tCO2e', 'Credit Value INR', 'Methodology', 'Status', 'Created'];
    const rows = [[
      record.mrv_id,
      record.farmer.name,
      record.farmer.mobile,
      record.farmer.village,
      record.farmer.block,
      record.farmer.district,
      record.land.area_ha,
      Object.entries(record.interventions).filter(([,v]) => v?.enabled).map(([k]) => k).join('; '),
      record.carbon.gross_tco2e,
      record.carbon.net_tco2e,
      record.carbon.credit_value_inr,
      record.carbon.methodology,
      record.status,
      record.created_at
    ]];
    MRVUtils?.downloadCSV(rows, headers, `${record.mrv_id}_MRV.csv`);
  }

  // ─── Map PNG Snapshot ────────────────────────────────────────

  async function exportMapPNG(leafletMap, record) {
    try {
      // Use leaflet-image or html2canvas if available
      if (window.leafletImage) {
        leafletImage(leafletMap, (err, canvas) => {
          if (err) { alert('Map snapshot failed.'); return; }
          canvas.toBlob(blob => {
            MRVUtils?._triggerDownload?.(blob, `${record.mrv_id}_map.png`);
          });
        });
      } else if (record.land?.map_snapshot_b64) {
        // Use stored snapshot
        const arr = record.land.map_snapshot_b64.split(',');
        const mime = arr[0].match(/:(.*?);/)[1];
        const bstr = atob(arr[1]);
        const n = bstr.length;
        const u8arr = new Uint8Array(n);
        for (let i = 0; i < n; i++) u8arr[i] = bstr.charCodeAt(i);
        const blob = new Blob([u8arr], { type: mime });
        const url = URL.createObjectURL(blob);
        const a = Object.assign(document.createElement('a'), { href: url, download: `${record.mrv_id}_map.png` });
        a.click(); setTimeout(() => URL.revokeObjectURL(url), 500);
      } else {
        alert('Map snapshot not available. Please save the record first.');
      }
    } catch (e) { console.error(e); alert('Map snapshot failed.'); }
  }

  return { exportPDF, exportJSON, exportGeoJSON, exportCSV, exportMapPNG };

})();

window.MRVExporter = MRVExporter;
